const mongoose = require('mongoose')

const Schema = mongoose.Schema

const usersSchema = new Schema({
    id:{
        type:Number
    },
    ip_address:{
        type:String
    },
    browser_name:{
        type:String
    },
    sharecoinexchange_fname:{
        type:String
    },
    sharecoinexchange_lname:{
        type:String
    },
    sharecoinexchange_username:{
        type:String
    },
    sharecoinexchange_password:{
        type:String
    },
    sharecoinexchange_email:{
        type:String
    },
    activation_code:{
        type:String
    },
    verification_code:{
        type:String
    },
    forgotten_password_code:{
        type:String
    },
    forgotten_password_time:{
        type:String
    },
    forgot_url:{
        type:String
    },
    remember_code:{
        type:String
    },
    created_on:{
        type:String
    },
    last_login:{
        type:String
    },
    first_name:{
        type:String
    },
    last_name:{
        type:String
    },
    profile_picture:{
        type:String
    },
    company:{
        type:String
    },
    dob:{
        type:String
    },
    phone_prefix:{
        type:String
    },
    sharecoinexchange_phone:{
        type:String
    },
    city:{
        type:String
    },
    country:{
        type:String
    },
    randcode:{
        type:String
    },
    secret:{
        type:String
    },
    verified:{
        type:String
    },
    register_from:{
        type:String
    },
    verification_level:{
        type:String
    },
    street_address:{
        type:String
    },
    street_address_2:{
        type:String
    },
    state:{
        type:String
    },
    postal_code:{
        type:String
    },
    photo_id_1:{
        type:String
    },
    photo_id_2:{
        type:String
    },
    photo_id_3:{
        type:String
    },
    verify_level2_status:{
        type:String
    },
    verify_level2_date:{
        type:String
    },
    photo_1_status:{
        type:String
    },
    photo_2_status:{
        type:String
    },
    photo_3_status:{
        type:String
    },
    photo_1_reason:{
        type:String
    },
    photo_2_reason:{
        type:String
    },
    photo_3_reason:{
        type:String
    },
    shasta_secure:{
        type:String
    },
    company_name:{
        type:String
    },
    company_regnumber:{
        type:String
    },
    representative_name:{
        type:String
    },
    representative_surname:{
        type:String
    },
    usertype:{
        type:String
    },
    shareholders_directors:{
        type:String
    },
    shareholding_structure:{
        type:String
    },
    company_address:{
        type:String
    },
    company_phone:{
        type:String
    },
    company_reg_document:{
        type:String
    },
    company_status:{
        type:String
    },
    profile_status:{
        type:String
    },
    kyc_status:{
        type:String
    },
    referral_code:{
        type:String
    },
    referral_name:{
        type:String
    },
    paypal_email:{
        type:String
    },
    merchant_id:{
        type:String
    },
    national_tax_number:{
        type:String
    }

    
   
},{timeseries:true})

const Users = mongoose.model('users',usersSchema)
module.exports = Users